### ISSUE TITLE
How can I get the total booking time for each projet?

### ISSUE THREAD

**Issue by fcouillard** [hubplanner/API#12]
I want to get total booking time for each project.

I'm using the Hubplanner API and I'm comparing the results with the "Active project" report in Hubplanner.

I'm pulling with the booking with start and end date between a specified month (start $gte 01-01-1000, end $let 30-01-1000). I'm using the API.

With PHP I'm looping each booking row, making the sum of each bookedMinutes for each Project. 

It seems some totals are fine, others don't match. 

Looking the "Active project" report, it seems I miss some booking entries. For example, for a project I get only 1 resource associated to it with the API, but in the report "Active project", there's 2 resources.

It seems I miss some booking entries. Or maybe something else. What am I doing wrong?

**Comment by thecodinglinguist** [comment]
Hi, 

I have opened a ticket and we will investigate this asap. Sorry for the delayed response.

**Comment by thecodinglinguist** [comment]
When you do a range query it needs to look like this to get everything within the range even if the booking might start outside of September like this example. In  your example you are missing one booking because you query start > 01 and the booking is actually starting on the 31st of August. 
{"start": {"$lte": "2015-09-30"}, "end":{"$gte": "2015-09-01"}}

Does that make sense?
