### ISSUE TITLE
Booking category

### ISSUE THREAD

**Issue by matto1990** [hubplanner/API#13]
Hi,

I'm looking to create bookings via the API, but there seems to be no documented way to choose a _category_ for the bookings I'm creating. Ideally I'd need:
1. An endpoint to get the list of _categories_
2. A way to send the category for the booking through the `POST /booking` endpoint

Thanks in advance!

Matt

**Comment by thecodinglinguist** [comment]
Hi Matt, 

Right now it is possible to set a category by adding categoryTemplateId to the booking update / create call. It is not documented yet as we have not exposed the endpoint to get all the categories yet. It is not ideal but you could of course get them by manually adding them to a few bookings and then retrieving them from the API. 

As it looks now we plan to release a v2 of the API early next year that will have the category endpoint and a lot of other improvements. 

Jonas

**Comment by matto1990** [comment]
Ah ok. It's likely we'll wait to implement this until the new APi is out. Do you have a more specific date for it?

We're creating a tool to create repeat booking easily (events that take place for every person every Monday for example). Currently the only feature missing is being able to choose and set the category of the booking that is being created.

**Comment by thecodinglinguist** [comment]
Sorry no dates yet. Final scope is still being planned and we are currently working on a couple of big updates that is scheduled for Christmas. Check in early January if I have not got back to you. I might be able to squeeze in your requests if we are being delayed. Those will go on the old API in that case.  There will not be much structure change on the V2 API so if you want to start the integration it will not be to much of a headache to upgrade later :) . The biggest change are added pagination for big search results and the possibility to delta update instead of sending the whole object on all update calls. We will also add endpoints for all new features such as categories, custom fields and tags.

**Comment by matto1990** [comment]
Thanks Jonas. I'll check back in the new year!
